version: '3.5'
services:
  react:
    container_name: electron 
    image: jungseoro/electron:wine-gecko
    stdin_open: true
    ports:
    - '3000:3000'
    volumes:
    - '/tmp/.X11-unix:/tmp/.X11-unix' 
    - ../:/vol
    environment:
    - DISPLAY=unix$DISPLAY
    - CMD=${CMD}
    tty: true   
    command: |
      sh -c 'cd /vol \
      && npm install \
      && npm run ${CMD:-start}'
