version: '3.5'
services:
  react:
    container_name: react
    image: jungseoro/electron:node${NODE_VERSION}
    stdin_open: true
    ports:
    - '3000:3000'
    volumes:
    - '/tmp/.X11-unix:/tmp/.X11-unix' 
    - ../:/vol
    environment:
    - DISPLAY=unix$DISPLAY
    tty: true   
    command: |
      sh -c 'cd /vol \
      && npm install \
      && npm start'
